### ISSUE TITLE
Images and anchors should be draggable by default

### ISSUE THREAD

**Issue by rubenlg** [timruffles/mobile-drag-drop#122]
But if I don't set that property explicitly, the polyfill doesn't work, although in desktop browsers it works fine. Tested on `<img>` only.

**Comment by reppners** [comment]
You're right! Thanks for reporting.

Which browser/os combinations do you use?

**Comment by rubenlg** [comment]
I use latest stable Chrome and Firefox. But I write a library that should also work on Edge (I haven't tested what happens on that one).

As a workaround in the meantime I'm setting draggable=true as a property in my images before configuring dragging, so this is not blocking me at all (i.e. not urgent).

**Comment by rubenlg** [comment]
Thanks!
