### ISSUE TITLE
README clarifications

### ISSUE THREAD

**Issue by LucasCioffi** [timruffles/mobile-drag-drop#133]
Thanks so much for making this shim!  It looks very promising and the demo works great.

Am I reading the installation instructions correctly?  This is how I read it: the minimum installation to get things working is to complete one option from step 1, one option from step 2 and all three under step 3.

Step 1. Choose one of the "Install" instructions:
- npm
- jspm
- bower

Step 2. Choose one of the "Include" options:
- global
- SystemJS/JSPM
- ES2015/TypeScript/webpack

Step 3. Follow the instructions under each of these three headings:
- Make sure to implement a dragenter-listener!
- If you're targeting iOS Safari 10.x and higher (optional)
- webpack/scss

**Comment by reppners** [comment]
Yes, this is correct. It's not really well structured, proposals for making it more clear are highly welcome!
