### ISSUE TITLE
Drag & Drop not working on Firefox (59.0.2 (64-Bit))

### ISSUE THREAD

**Issue by tobiasfiechter** [timruffles/mobile-drag-drop#134]
Somehow drag and drop does not work with Firefox Version 59.0.2 (64-Bit) in Touch mode.

This can be reproduced when visiting: http://timruffles.github.io/mobile-drag-drop/demo/ and emulating Mobile devices.

**Comment by reppners** [comment]
Welcome and thanks for reporting. I'll try to have look the next couple of days. Did you try the `forceApply` config parameter set to true?

**Comment by reppners** [comment]
Confirming its not working in FF59 in mobile device emulation mode. I highly suspect its not working because it's not detected as lacking drag and drop support.

Firefox 60 does work (at least in mobile device emulation mode).

**Comment by reppners** [comment]
Closing as non-actionable browser issue since it's resolved in current version of Firefox.
