### ISSUE TITLE
holdToDrag and custom styling

### ISSUE THREAD

**Issue by rmeshksar** [timruffles/mobile-drag-drop#136]
Hi,
Thank you so much for the great library.
I would like to apply a specific styling to the element when the dragging is getting enabled after some interval using holdToDrag. For example apply scaling of 95% to the div to show now it can be dragged.

Wondering what is the best way of doing this?

Thanks,.

**Comment by reppners** [comment]
Hi, thank you, glad you like it.

At the moment it is not possible without changes to the polyfill.

It could be achieved by firing a custom event on the draggable element when the drag operation is initialized and pending to start on first touchmove event. You could then listen for this event and apply a css class.

**Comment by anwarjaved** [comment]
I have pushed a [PR](https://github.com/timruffles/mobile-drag-drop/pull/150) to support this.

**Comment by reppners** [comment]
Implemented by #150, thanks to @anwarjaved 👍
