### ISSUE TITLE
holdToDrag and moving touch point

### ISSUE THREAD

**Issue by rmeshksar** [timruffles/mobile-drag-drop#138]
Hi,
I want to use holdToDrag but only if touch point stays in the same position, but currently if I touch the element and keep moving that touch point right away, after the holdToDrag time the element starts to move.

Is the any way to cancel the drag in that case?

Thanks.

**Comment by reppners** [comment]
Hmm sounds like a bug to me. Dragstart should be canceled when moving while holdToDrag timer runs.

**Comment by parveenkhtkr** [comment]
Might be helpful to know, I had this same issue on iOS 11.4.1 Safari. Though, after RTFM and adding `window.addEventListener('touchmove', function () { }, { passive: false })` I am no longer able to reproduce it.

**Comment by parveenkhtkr** [comment]
hmm it still happens very rarely, when I get a lucky flick where it happens to be start of scrolling and at the same moment transitioning into drag state. If that makes sense.

**Comment by reppners** [comment]
Thanks for sharing your findings and yes the behavior you describe makes perfect sense. It is hard to get this just right to make it work in all cases :-/

**Comment by reppners** [comment]
I've added `touchmove` to the events that cancel a pending dragstart. This should fix it, if the issue still persists ping here and I'll reopen.
