### ISSUE TITLE
Add the possibility to decide if the holdToDrag delay should be applied or not

### ISSUE THREAD

**Issue by Mboulianne** [timruffles/mobile-drag-drop#140]
Hello,
I'm having a small issue on PC / laptops with a touch enabled screen.

1- When I try to drag and drop using the touch screen the holdToDrag delay is being applied.  All is good and feel very natural.
2- Then I take the mouse and try to drag.  The holdToDrag delay is still there and it doesn't feel natural at all.  We are used to drag and drop right away with a mouse.

I'd like to have a hook that allows me to tell the polyfill if it should go on and apply the delay.

Does it make sense to you?

**Comment by reppners** [comment]
Welcome :)

So your PC is emulating touch events when using the mouse? Thats basically the issue. If you're using a mouse there should be mouse events. The polyfill only picks up on touch events.

Theres two options
* find a way to configure the machine/browser to emit mouse events when a mouse is used
* find a way to discern emulated touch events when using the mouse from touch events (polyfills features a hook to decide if drag should start based on the touch event), but I'm pretty sure this is rather impossible.

**Comment by reppners** [comment]
Closing because as of now this is non-actionable. Will reopen if discussion leads to actionable outcome.
