### ISSUE TITLE
dragImageCenterOnTouch and dragOffset not working

### ISSUE THREAD

**Issue by AndrewMorsillo** [timruffles/mobile-drag-drop#142]
Using either of these options the drag image's top left corner is always at the touch point. I have tested it on iOS 12 and Android Chrome. I'm not really sure how to debug this.

**Comment by reppners** [comment]
Thanks for your bug report. Can you please provide details about the version you're using plus the config you use to initialize the polyfill?

**Comment by AndrewMorsillo** [comment]
I'm using 2.3.0-rc.1. My configuration is as so:

```
polyfill({
    dragImageCenterOnTouch: true,
    holdToDrag: bowser.mobile ? 150 : 0
})
```

I tried dragOffset as well with no effect. I'm using this library with react-dnd in my app.

**Comment by reppners** [comment]
Sorry for not getting back to this.. if you can provide some sample code I may be able to look into it. Until then I assume it's a specific CSS styling issue. Closing but happy to reopen when this issue becomes actionable!
