### ISSUE TITLE
How to enforce ie11 to use the polyfill instead of native drag-drop?

### ISSUE THREAD

**Issue by hkkhchan** [timruffles/mobile-drag-drop#145]
I would like to use the shadow DOM with polyfill. but when the platform is desktop. 
It will use the native drag-drop even I already set the config as
```
    polyfill({
      dragImageTranslateOverride: scrollBehaviourDragImageTranslateOverride,
      forceApply: true
    });
```

**Comment by reppners** [comment]
This polyfill does only apply to touch events so I think it won't work with IE11. As far as shadow dom support is concerned you can check #115

**Comment by hkkhchan** [comment]
I wonder if using mouse event in ie 11 can make it work. but it seem complicated.

For solving my issue, I use drag event to update the position of shadow dom. but the moving is not smooth because the drag event don't fire on real time.

**Comment by reppners** [comment]
Closing as non actionable. ShadowDOM support is tracked by #115.
