### ISSUE TITLE
Body scroll vs container scroll

### ISSUE THREAD

**Issue by franciscolourenco** [timruffles/mobile-drag-drop#149]
Is the scroll supposed to be prevented on scrollable areas as well, or only on body scroll?

**Comment by reppners** [comment]
I'm not sure I can follow. Scrolling while dragging should only happen when using MobileDragDrop.scrollBehaviourDragImageTranslateOverride and dragging close to an edge of the viewport.

The discussion/workaround in https://github.com/timruffles/mobile-drag-drop/issues/124 might be of interest for you.

**Comment by franciscolourenco** [comment]
I'm using the workaround but scroll is not prevented in scrollable areas besides the body. Is this case supposed to be covered as well?

**Comment by reppners** [comment]
Scrollable areas should behave just the same as the body. Meaning scroll should only start if hovering at an edge of the scrollable area.

**Comment by franciscolourenco** [comment]
@reppners is scroll prevented on your iOS device? 
https://codesandbox.io/s/vue-template-giu2u
https://giu2u.codesandbox.io/

**Comment by reppners** [comment]
The workaround you've applied does not work for iOS 11.3 and newer as discussed in #124. 

Please try `window.addEventListener('touchmove', function () { }, {passive: false})`
https://codesandbox.io/s/vue-template-75hkx

**Comment by reppners** [comment]
Closing as solved. If you disagree feel free to ping here and I'll reopen.
