### ISSUE TITLE
Can't work iPadOS(iOS 13.1.2)

### ISSUE THREAD

**Issue by maedana** [timruffles/mobile-drag-drop#152]
iPadOS and MacOS are return same user-agent. So below code is not work well on iPadOS.
https://github.com/timruffles/mobile-drag-drop/blob/2b7ac0a254752ef0207a8e1ed2f573f427ca1c14/src/internal/feature-detection.ts#L17-L23

My workarround is below.
```
import { polyfill } from 'mobile-drag-drop'
import { scrollBehaviourDragImageTranslateOverride } from 'mobile-drag-drop/scroll-behaviour'

const ua = window.navigator.userAgent.toLowerCase()
const isiPad = ua.indexOf('ipad') > -1 || (ua.indexOf('macintosh') > -1 && 'ontouchend' in document)

const usePolyfill = polyfill({
  forceApply: isiPad, // force apply for ipad
  dragImageTranslateOverride: scrollBehaviourDragImageTranslateOverride || isiPad,
})

if (usePolyfill) {
  document.addEventListener('dragenter', (event) => event.preventDefault())
  window.addEventListener('touchmove', () => {}, { passive: false })
}
```

**Comment by evanb2** [comment]
Which browsers were you experiencing this on? Our drag-n-drop code broke on iPadOS on Safari only with the latest release.

**Comment by steveszc** [comment]
More context here: https://forums.developer.apple.com/thread/119186

**Comment by reppners** [comment]
Closing this as it is superseded by https://github.com/timruffles/mobile-drag-drop/issues/167 and a workaround is provided!
