### ISSUE TITLE
Console pollution

### ISSUE THREAD

**Issue by VasylMarchuk** [timruffles/mobile-drag-drop#153]
Hi!

Is there a way to prevent `mobile-drag-drop` from polluting the console output?

<img width="227" alt="Знімок екрана 2020-03-25 о 17 43 25" src="https://user-images.githubusercontent.com/493875/77555693-3890a080-6ec0-11ea-9e66-cec70f66418c.png">

Thanks

**Comment by reppners** [comment]
Hi! Try the minified js, it should not produce verbose logging.

**Comment by VasylMarchuk** [comment]
Hello again! We are using `mobile-drag-drop` as an `npm` package in our Ember.js project, and non-minified source is getting included in our non-minified `vendor.js` somewhere in the Ember build pipeline. Unfortunately it doesn't look like it's trivial to force Ember to use the minified file.

**Comment by reppners** [comment]
Are you using `ember-auto-import`? Maybe this can help to point to the minified version: https://github.com/ef4/ember-auto-import#customizing-build-behavior?

**Comment by VasylMarchuk** [comment]
Thanks, this seems like the right direction to go to!
