### ISSUE TITLE
[Question] Using without any package manager

### ISSUE THREAD

**Issue by ShadabFaiz** [timruffles/mobile-drag-drop#154]
How can I use it without any package manager, with just plain HTML/ js? Any CDN available?

**Comment by reppners** [comment]
Hi,

no CDN available, but maybe https://unpkg.com/ works for you.

**Comment by ShadabFaiz** [comment]
Ok. Thanks for the information

**Comment by sheffieldnick** [comment]
For anyone else looking for this library on a CDN: [https://unpkg.com/mobile-drag-drop@2.3.0-rc.2/index.min.js](https://unpkg.com/mobile-drag-drop@2.3.0-rc.2/index.min.js)
