### ISSUE TITLE
tags with href become draggable

### ISSUE THREAD

**Issue by marijus-saulys** [timruffles/mobile-drag-drop#156]
After enabling polyfill, all elements with hrefs become draggable with no additional attributes specified. You have to explicitly define draggable='false' on all of them to fix the issue. 

I expect to define draggable='true' on elements which I want to be dragged, not vice versa. Am I missing something?

Issue can be reproduced on mobile browsers or in mobile view from desktop browser. Tested on Google Chrome Version 83.0.4103.97 (Official Build) (64-bit)

**Comment by Fourie-r** [comment]
Having the same issue +1

**Comment by aaronzufall** [comment]
I also had this issue and found that specifying this as an option was a functional workaround for me (using TypeScript):
`dragStartConditionOverride: (event:TouchEvent) => { return (event.target as HTMLElement).closest('[draggable=true]') !== null },`

**Comment by reppners** [comment]
Closing because a workaround is available and `a` tags are draggable by default as per the HTML5 spec.
