### ISSUE TITLE
Firing any drag event disables dataTransfer

### ISSUE THREAD

**Issue by sorentycho** [timruffles/mobile-drag-drop#158]
It looks like the offending line is: https://github.com/timruffles/mobile-drag-drop/blob/2b7ac0a254752ef0207a8e1ed2f573f427ca1c14/src/internal/drag-utils.ts#L146 

This unconditionally disables the dataStore as soon as any drag event fires, which makes it impossible to e.g. have both a `dragenter` and `drop` handler, and still use `event.dataTransfer`.

I'd prepare a PR, but I'm not actually clear as to why the data store can *be* disconnected?

**Comment by reppners** [comment]
Thanks for reporting and to be honest - I have no idea why the disconnect was introduced. Either to align with desktop browser drag and drop implementations or to resolve some observed glitches while developing/testing the polyfill. 

Before each drag event dispatch the mode is set appropriately so the data store can be accessed in the event handlers that are triggered by the dispatched event. After the event has been fired the datastore is disconnected to prevent access. 

What bug or issue where you observing?

**Comment by reppners** [comment]
If the current behaviour of the datastore causes you trouble, please comment and explain the way it is affecting you and I'll reopen to discuss it.
