### ISSUE TITLE
issue: the element moving is delay when dragging

### ISSUE THREAD

**Issue by eeeeeeeason** [timruffles/mobile-drag-drop#163]
vedio are as follow
https://github.com/eeeeeeeason/dailybug/blob/main/BAQIS%20Cloud%20development%20-%20Google%20Chrome%202021-07-06%2018-02-10.mp4

**Comment by eeeeeeeason** [comment]
finally ,i guest this was something wrong with my css but not  js. after i deleted the css attribute "transition: transform .5s; "  i find that everything is ok; and i begin to read through the repo; can i add an filter to prevent the trasition attribute copy from the origin element? if it is ok  , i would like to commit a pr. i'm looking forward to hearing from you

**Comment by eeeeeeeason** [comment]
thanks this great repo .

**Comment by reppners** [comment]
Thanks for the PR!
