### ISSUE TITLE
issue: element can't be dragged while remove the old element

### ISSUE THREAD

**Issue by eeeeeeeason** [timruffles/mobile-drag-drop#165]
although i run the demo and i find all the dragging element are existed when it was dragged. and unfortunately my work need to remove the old child when it was drag , if it has any hack way(exclude hide the old element) to handle this problem? thanks alot

**Comment by reppners** [comment]
Hide the dragged element while the drag operation is ongoing via css. When the drag operation completes remove the dragged element from the DOM as necessary. If you need sample code, let me know.
